# Generated by agent — review required
# prompt_hash: PROMPT_1_SHA256

import pytest
import json
from models.adapter_manifest import validate_manifest

VALID_MANIFEST = {
  "schema_version": "2026-08-1",
  "adapter_id": "0123456789abcdef_0123456789abcdef",
  "created_at": "2026-08-30T12:00:00+00:00",
  "source_fingerprint": "src123",
  "target_fingerprint": "tgt123",
  "mapping_policy": {},
  "dependency_versions": {"pydantic": "2.x"},
  "validation_authority": "team@example.com",
  "models_used": ["model-x"],
  "synthesis_mode": "single_pass",
  "context_references": [],
  "fixture_ids": [],
  "test_result": "passed",
  "lossiness": [],
  "redactions": [],
  "status": "proposed"
}

INVALID_MISSING_FIELD = VALID_MANIFEST.copy()
INVALID_MISSING_FIELD.pop('adapter_id')

INVALID_WRONG_TYPE = VALID_MANIFEST.copy()
INVALID_WRONG_TYPE['models_used'] = "not-a-list"

INVALID_ENUM = VALID_MANIFEST.copy()
INVALID_ENUM['status'] = 'unknown-status'


def test_valid_manifest():
    ok, errors = validate_manifest(VALID_MANIFEST)
    assert ok is True
    assert errors == []


def test_missing_required_field():
    ok, errors = validate_manifest(INVALID_MISSING_FIELD)
    assert ok is False
    assert any('adapter_id' in str(e.get('loc') or '') or 'adapter_id' in e.get('message','') for e in errors)


def test_wrong_type():
    ok, errors = validate_manifest(INVALID_WRONG_TYPE)
    assert ok is False
    assert any('models_used' in str(e.get('loc') or '') for e in errors)


def test_invalid_enum():
    ok, errors = validate_manifest(INVALID_ENUM)
    assert ok is False
    assert any('status' in (e.get('loc') or '') or 'status' in e.get('message','') for e in errors)
