# Generated by agent — review required
# prompt_hash: PROMPT_1_SHA256

"""
CLI validator for adapter manifests.
Usage:
  python scripts/validate_manifest.py adapters/<adapter_id>/manifest.json
  python scripts/validate_manifest.py --root adapters/

Exit codes:
  0 = all valid
  2 = validation error(s) found
  3 = usage / other error

"""
from __future__ import annotations
import argparse
import json
import sys
import os
from typing import List, Dict, Any

from models.adapter_manifest import validate_manifest
import jsonschema


def find_manifests(root: str) -> List[str]:
    manifests = []
    for dirpath, dirnames, filenames in os.walk(root):
        for fn in filenames:
            if fn == 'manifest.json':
                manifests.append(os.path.join(dirpath, fn))
    return manifests


def main(argv: List[str] | None = None) -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument('path', nargs='?', help='Path to manifest.json or adapter directory')
    parser.add_argument('--root', help='Validate all adapters under a root directory')
    parser.add_argument('--format', choices=['json','text'], default='json')
    args = parser.parse_args(argv)

    targets: List[str] = []
    if args.root:
        if not os.path.isdir(args.root):
            print(json.dumps({"error": "root not found"}))
            return 3
        targets = find_manifests(args.root)
    elif args.path:
        if os.path.isdir(args.path):
            m = os.path.join(args.path, 'manifest.json')
            if os.path.exists(m):
                targets = [m]
            else:
                print(json.dumps({"error": f"manifest.json not found in {args.path}"}))
                return 3
        elif os.path.isfile(args.path):
            targets = [args.path]
        else:
            print(json.dumps({"error": "path not found"}))
            return 3
    else:
        parser.print_help()
        return 3

    overall_ok = True
    results = []
    for t in targets:
        ok, errors = validate_manifest(t)
        results.append({"file": t, "valid": ok, "errors": errors})
        if not ok:
            overall_ok = False

    if args.format == 'json':
        print(json.dumps(results, indent=2))
    else:
        for r in results:
            print(f"FILE: {r['file']} VALID: {r['valid']}")
            for e in r['errors']:
                print(f"  - {e}")

    return 0 if overall_ok else 2


if __name__ == '__main__':
    rc = main()
    sys.exit(rc)
