# Generated by agent — review required
# prompt_hash: PROMPT_1_SHA256

from __future__ import annotations
from pydantic import BaseModel, Field, ValidationError, model_validator
from typing import Any, Dict, List, Tuple
from datetime import datetime
import json
import re

ADAPTER_ID_RE = re.compile(r"^[0-9a-f]{16}_[0-9a-f]{16}$")

class GeneratorMeta(BaseModel):
    name: str
    version: str
    prompt_hash: str
    timestamp: str

class AdapterManifest(BaseModel):
    schema_version: str
    adapter_id: str = Field(..., description="Canonical adapter id; expected hex format")
    created_at: str
    source_fingerprint: str
    target_fingerprint: str
    mapping_policy: Dict[str, Any]
    dependency_versions: Dict[str, str]
    validation_authority: str
    models_used: List[str]
    synthesis_mode: str
    context_references: List[str]
    fixture_ids: List[str]
    test_result: str
    lossiness: List[str]
    redactions: List[str]
    status: str
    generator: GeneratorMeta | None = None

    @model_validator(mode='after')
    def check_adapter_id_and_timestamp(cls, values: 'AdapterManifest') -> 'AdapterManifest':
        # Validate adapter_id format
        if not ADAPTER_ID_RE.match(values.adapter_id):
            raise ValueError(f"adapter_id {values.adapter_id!r} does not match required format")
        # Validate created_at timestamp
        try:
            datetime.fromisoformat(values.created_at)
        except Exception as e:
            raise ValueError(f"created_at must be RFC3339/ISO timestamp: {e}")
        # Validate enums
        if values.synthesis_mode not in ("single_pass", "two_pass", "repair_attempt"):
            raise ValueError("synthesis_mode must be one of single_pass, two_pass, repair_attempt")
        if values.test_result not in ("passed", "failed", "skipped"):
            raise ValueError("test_result must be passed, failed, or skipped")
        if values.status not in ("proposed","valid","stale","invalid","deprecated"):
            raise ValueError("status must be proposed, valid, stale, invalid, or deprecated")
        return values


def validate_manifest(path_or_dict: str | Dict[str, Any]) -> Tuple[bool, List[Dict[str, Any]]]:
    """Validate a manifest either from a path or from a dict.

    Returns (is_valid, errors) where errors is a list of dicts {"message":..., "loc":...}
    """
    data = None
    errors: List[Dict[str, Any]] = []
    if isinstance(path_or_dict, str):
        try:
            with open(path_or_dict, 'r', encoding='utf-8') as f:
                data = json.load(f)
        except Exception as e:
            return False, [{"message": f"failed to read file: {e}", "loc": [path_or_dict]}]
    else:
        data = path_or_dict

    # Pydantic validation
    try:
        AdapterManifest.model_validate(data)
    except ValidationError as ve:
        for err in ve.errors():
            errors.append({
                "message": err.get('msg'),
                "loc": err.get('loc'),
                "type": err.get('type')
            })
        return False, errors
    except Exception as e:
        return False, [{"message": f"unexpected validation error: {e}", "loc": []}]

    return True, []
