"""Generated by Manus-assisted change — review required."""
from __future__ import annotations

import json
from pathlib import Path
from typing import Any

from pydantic import BaseModel, ConfigDict, Field, ValidationError, field_validator


class AdapterManifest(BaseModel):
    model_config = ConfigDict(extra="allow")

    schema_version: str = Field(min_length=1)
    adapter_id: str = Field(min_length=3)
    created_at: str
    source_fingerprint: str = Field(pattern=r"^[a-f0-9]{16}$")
    target_fingerprint: str = Field(pattern=r"^[a-f0-9]{16}$")
    mapping_policy: dict[str, Any]
    dependency_versions: dict[str, Any]
    validation_authority: str = Field(min_length=1)
    models_used: list[str]
    synthesis_mode: str
    context_references: list[str]
    fixture_ids: list[str]
    test_result: str
    lossiness: list[str]
    redactions: list[str]
    status: str

    @field_validator("synthesis_mode")
    @classmethod
    def valid_synthesis_mode(cls, value: str) -> str:
        if value not in {"single_pass", "two_pass", "repair_attempt"}:
            raise ValueError("synthesis_mode must be single_pass, two_pass, or repair_attempt")
        return value

    @field_validator("test_result")
    @classmethod
    def valid_test_result(cls, value: str) -> str:
        if value not in {"passed", "failed", "skipped"}:
            raise ValueError("test_result must be passed, failed, or skipped")
        return value

    @field_validator("status")
    @classmethod
    def valid_status(cls, value: str) -> str:
        if value not in {"proposed", "valid", "stale", "invalid", "deprecated"}:
            raise ValueError("status must be proposed, valid, stale, invalid, or deprecated")
        return value


def validate_manifest(path_or_dict: str | Path | dict[str, Any]) -> tuple[bool, list[str]]:
    try:
        if isinstance(path_or_dict, (str, Path)):
            data = json.loads(Path(path_or_dict).read_text(encoding="utf-8"))
        else:
            data = path_or_dict
        AdapterManifest.model_validate(data)
        return True, []
    except (OSError, json.JSONDecodeError, TypeError, ValueError, ValidationError) as exc:
        if hasattr(exc, "errors"):
            errors = [f"{'.'.join(str(x) for x in item.get('loc', []))}: {item.get('msg', 'invalid')}" for item in exc.errors()]
        else:
            errors = [str(exc)]
        return False, errors
